spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/banking-services-backend
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: obetabyte@gmail.com
#    password: mjaa bocc zauu njqy
    password: regpvghhixbvhjws
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: banking-services-backend
server:
  port: '8080'
